//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.Buys = new HashSet<Buy>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int sellCrerk_id { get; set; }
        public int customer_id { get; set; }
    
        public virtual ICollection<Buy> Buys { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
