//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kala
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kala()
        {
            this.Buys = new HashSet<Buy>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string producer { get; set; }
        public System.DateTime creatDate { get; set; }
        public System.DateTime expireDate { get; set; }
        public int price { get; set; }
        public int quantity { get; set; }
        public int discount { get; set; }
        public string seller { get; set; }
        public System.DateTime submitDate { get; set; }
        public int stockClerk_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buy> Buys { get; set; }
        public virtual User User { get; set; }
    }
}
